FROM golang:1.25-alpine

RUN apk add --no-cache \
      gcc \
      g++ \
      make \
      vips-dev \
      git \
      curl

RUN go install github.com/air-verse/air@latest

RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN mkdir -p tmp

EXPOSE 8080

CMD ["task"]